### ISSUE TITLE
Add grade type property

### ISSUE THREAD

**Issue by bntti** [aalto-grades/aalto-grades#699]
Right now only `A+` or `manual` I think.
- This can be inferred from the A+ id or the absence of one?

**Comment by gubo97000** [comment]
is csv manual? I guess yes

**Comment by no-comma** [comment]
Right now we are indeed inferring whether a grade is an A+ grade based on whether an A+ grade source is defined. With this in place, I don't think we want a grade type property at all right now. The reason I think we would have wanted this is because it overlaps with #700, but I think we could just implement #700 right now and change the override field to a generic type field later if we need it for whatever reason.

**Comment by bntti** [comment]
Tracked in #867
